language: java
notifications:
  email:
    on_success: never 
    on_failure: never 

script:
 - if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]]; then
    curl -i -X POST  -d $TRAVIS_REPO_SLUG http://vicinity.iot.linkeddata.es/reqmanager/rest/hook/ &&
    curl -i -X POST  -d $TRAVIS_REPO_SLUG http://vicinity.iot.linkeddata.es/reqmanager/rest/hook &&
    response=$(curl -i -X POST  -d $TRAVIS_REPO_SLUG  http://vicinity.iot.linkeddata.es/reqmanager/rest/test/) &&  echo ${response} &&
    if [[ ${response} == *"WARNING"* ]] || [[ ${response} == *"ERROR"* ]]; then
      exit 1;
    fi;
   fi
